### ISSUE TITLE
Kelvin conversion

### ISSUE THREAD

**Issue by timrichardson** [adamesch/elgato-key-light-api#2]
"To convert values from Kelvin back to the API format, just divide 1.000.000 by the amount of Kelvin and round to the closest natural number."
are you sure about this? Or maybe I misread it. 

If 2900K maps to 143 and and 7000K to 344, the mean conversion is to divide kelvin by about 20.31

**Comment by adamesch** [comment]
honestly, i can't remember how i got the math to work out, but i updated the readme with clearer instructions. basically, use 0.05 as your scalar:

143 / 0.05 = 2860 (~2900K)
344 / 0.05 = 6880 (~6900K)

**Comment by adamesch** [comment]
here's the commit: https://github.com/adamesch/elgato-key-light-api/commit/e2bcf81f6f53cd4401790714d77b8c4595d88ce4
